### ISSUE TITLE
Question about the DeploymentPhaseType check in Pipeline Generator

### ISSUE THREAD

**Issue by KiLLeRRaT** [f2calv/yamlizr#103]
Hi,

I just want to check, what is the reason for restricting the `PhaseType` to only `DeployPhaseTypes.AgentBasedDeployment`?

https://github.com/f2calv/yamlizr/blob/799b5e068f18af758f1f67815abbf2566d164cb5/src/CasCap.Apis.AzureDevOps/Utilities/YamlPipelineGenerator.cs#L239

Thanks for a nice tool!

Cheers,

**Comment by f2calv** [comment]
I'm glad you find the tool useful :)

To answer your question;

- **DeployPhaseTypes.AgentBasedDeployment** is 1-to-1 with a YAML Deployment Job so that was straightforward to code against.
- **DeployPhaseTypes.RunOnServer** had no YAML alternative when I wrote the tool a year ago, however some months ago the PG released the [Manual Validation task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/manual-validation) which could maybe be shoehorned in somehow...

For **DeployPhaseTypes.DeploymentGates** and **DeployPhaseTypes.MachineGroupBasedDeployment** I have no experience working with nor any test environment set-up to guess my way through.

Happy to review a PR against any of the missing enums.
